### ISSUE TITLE
Parse error: syntax error, unexpected '->' (T_OBJECT_OPERATOR)

### ISSUE THREAD

**Issue by AlexL777** [mecha-cms/extend.panel#1]
Hi @tovic ,

I have a problem in the URL https://mechacms.wpzweinull.ch/panel/::g::/state

There is something with "Languages". The error in the backend, where I have the debug mode to "true", looks like this.

    Parse error: syntax error, unexpected '->' (T_OBJECT_OPERATOR) in /www/xxxxxxxxxx/mechacms.wpzweinull.ch/lot/extend/panel/lot/worker/page/state.php on line 42

Can you please take a look.

I have installed the very last branch with Mecha and also use the last panel extension.

Thanks in advance.

**Comment by tovic** [comment]
Fixed in the last commit.
