### ISSUE TITLE
Fatal error: Call to a member function avatar() on boolean in lot/extend/panel/lot/worker/nav.php on line 32

### ISSUE THREAD

**Issue by AlexL777** [mecha-cms/extend.panel#2]
Hi @tovic 

I have uploaded the new panel update and wanted to create new users in Mecha v2. But after the forwarding according to the adjustment of the Readme.md here comes an error, which looks like this.

    Fatal error: Call to a member function avatar() on boolean in /xxxxxxxxxxxxxxxxxx/mechacms.wpzweinull.ch/lot/extend/panel/lot/worker/nav.php on line 32

Panel-URL is as follow: `xxxxxxxx/panel/::s::/set`

Can you please see it again. Possibly important for all new users who also have to create the new user.

Thanks in advance.

**Comment by tovic** [comment]
Fixed now.
