### ISSUE TITLE
For Create a new User - Field "Name" not worked

### ISSUE THREAD

**Issue by AlexL777** [mecha-cms/extend.panel#3]
I just try to create a new user. The field "Name" has DropDown, but can not be opened and you can not enter a name.

Can check this again. Thanks and here is a screenshot.

![mechav2cms-create-new-user-field-name-not-worked](https://cloud.githubusercontent.com/assets/7885632/26006817/2bbafe9e-373e-11e7-9895-261237694fc0.jpg)

**Comment by tovic** [comment]
Huh, a drop down?

**Comment by tovic** [comment]
Oh, I see. You are using my old `user` extension which has a filter that will replace a text input with `name` of `author` into a select element. Previously I made the `user` extension as an optional dependency for the `panel` extension.

Try to change `user` extension with the new one by deleting and reuploading, not by overwritting.

**Comment by AlexL777** [comment]
Thanks, is fixed and I had outdated files of such extensions as "Tag, User etc.". Now the backend is working again.
