### ISSUE TITLE
Warning: Cannot use a scalar value as an array in

### ISSUE THREAD

**Issue by AlexL777** [mecha-cms/extend.panel#4]
Hi @Tovic,

I have a new issue with the panel extension.

The bugs that come after updating a blog post look like this. 

```
Warning: Cannot use a scalar value as an array in /xxxxxxxxxxxxxxxx/mechacms.wpzweinull.ch/lot/extend/panel/lot/worker/page/-t.php on line 20

Warning: array_replace_recursive(): Argument #1 is not an array in /xxxxxxxxxxxxxxxxxxx/mechacms.wpzweinull.ch/lot/extend/panel/lot/worker/page/-t.php on line 23

Warning: Cannot use a scalar value as an array in /xxxxxxxxxxxxxxxx/mechacms.wpzweinull.ch/lot/extend/panel/lot/worker/page/-t.php on line 23
```

Publish is not possible.

Can you please look after it. Thank you.

**Comment by tovic** [comment]
OK thanks.

**Comment by AlexL777** [comment]
Is this issue still current or could you fix it already?

I tried to upload the panel extension again. Unfortunately the same problem.

**Comment by AlexL777** [comment]
`Warning: Cannot use a scalar value as an array in /xxxxxxxx/mechacms.wpzweinull.ch/lot/extend/panel/lot/worker/page/-t.php on line 20`

Thank you for your interest in this issue. Unfortunately, the problem continues. Now this error message is displayed to me.

**Comment by AlexL777** [comment]
Hi @tovic ,

big Thanks for the Fix. 

The panel now seems to work again. So you can close this issue now. Thanks again.
